export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const LOAD_DATA_INTO_DB_REQUEST = "LOAD_DATA_INTO_DB_REQUEST";
export const LOAD_DATA_INTO_DB_SUCCESS = "LOAD_DATA_INTO_DB_SUCCESS";
export const LOAD_DATA_INTO_DB_FAIL = "LOAD_DATA_INTO_DB_FAIL";